hibernate.connection.driver_class=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# For Automation project, you usually don't change schema defined by business rules
hibernate.hbm2ddl.auto=none